### ISSUE TITLE
slickスライダーの自動再生

### ISSUE THREAD

**Issue by Toshiki-Shimosawa** [Toshiki-Shimosawa/web180#3]
Slickスライダーの自動再生が機能せず、画像が固定表示されるのみになってしまう。

**Comment by ProjectEuropa** [comment]
https://github.com/Toshiki-Shimosawa/web180/blob/6f7ba39c75334b2d0fb9924468b01209c1376d22/resources/views/index.blade.php#L10

**Comment by ProjectEuropa** [comment]
このテーマファイルがない気がします。

**Comment by ProjectEuropa** [comment]
https://gyazo.com/74acb5db7433ed13f5914c708ff068d7
